### PR TITLE
Added section "Tips & Tricks" to README.md

### PR DESCRIPTION
**Pull request by porg**

### CODE REVIEW

**Comment by porg** [comment]
Hi @nk9 could you please help to merge that into the appropriate section?
- I am currently not good at git / github, would love if you could resolve that merge conflict on my behalf adequately.
- Would love if this useful hints make it into the readme.

**Comment by nk9** [comment]
Thanks for the suggestions. The `sed` part is unnecessary now that the `--query` argument lets you modify the returned query parameters in a robust way. And the first bit just restates how to use the command which is described in the Usage section of the README already. So I don't see much benefit to adding this PR.

**Comment by porg** [comment]
I agree:
- **Shell globing** as an easy means to submit multiple files of a series  is shown in the readme (meanwhile)
- **sed** string manipulation is indeed not necessary having `--query` now.

**Comment by porg** [comment]
FYI: Though I will need `sed` for post-processing of the subdomain/domain part as long as not having:
- #13

**Pull request closed without merging**
